### ISSUE TITLE
Large spot price discrepancies

### ISSUE THREAD

**Issue by pmknutsen** [grosskur/ec2price#3]
I've noticed large price discrepancies with the Price History in the EC2 Management Console.

Here's what the ec2price.com site shows for g2.8xlarge spot instances:
![screenshot from 2016-04-02 16 43 36](https://cloud.githubusercontent.com/assets/1565499/14229820/c2b853da-f8f3-11e5-9560-89d12da03222.png)

and the corresponding spot instance price for same type, location(s) and time period in the EC2 Management Console:
![screenshot from 2016-04-02 16 43 09](https://cloud.githubusercontent.com/assets/1565499/14229822/da576760-f8f3-11e5-99da-9ce65a99281e.png)

**Comment by grosskur** [comment]
Can you try changing the dropdown on ec2price.com to "Linux/UNIX (Amazon VPC)"? I think that will make them look the same.

It's not entirely clear from the ec2price.com UI, but "Linux/UNIX" refers to the legacy EC2 Classic environment which most people don't use and has different spot prices.

**Comment by pmknutsen** [comment]
Thanks, that did it. I didn't even know there were different EC2-VPC and EC2-Classic instances. Prices correspond now that I select EC2-VPC.
